### ISSUE TITLE
car wheel issue

### ISSUE THREAD

**Issue by imcreativeaboutusernames** [Gann4Games/Thirdym#19]
walking into the car's wheels kills you even if the car isnt moving

**Comment by Gann4** [comment]
Wheel colliders have a plain disk shape, that could be the main issue, however it will be replaced whenever i decide to work on vehicles again from scratch, because i'm using free assets to build vehicles with wheels.

I'll not close this so i can remember later to work on vehicles, but it wont get fixed at all. :)

**Comment by Gann4Life** [comment]
Vehicles have been removed.
